config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :todo_lists do
    resources :items
  end

  resources :items

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :todo_list

  def get_state
    if self.done == true
      $result = 'Done!'
    else
       $result =  'lots to do!'
    end
    $result
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @todo_list = TodoList.find(params[:todo_list_id])
    @item = @todo_list.items.create(item_params)
    redirect_to todo_list_path(@todo_list)
  end

  def edit
    @todo_list = TodoList.find(params[:todo_list_id])
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @todo_list = TodoList.find(@item.todo_list_id)
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @todo_list, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @todo_list = TodoList.find(@item.todo_list_id)
    @item.destroy
    respond_to do |format|
      format.html { redirect_to @todo_list, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 
  private
    def item_params
      params.require(:item).permit(:title, :done)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]


  def index
    @todo_lists = TodoList.all
  end

  def new
    @todo_list = TodoList.new
  end

 
  def create
    @todo_list = TodoList.new(todo_list_params)
 
    @todo_list.save
    redirect_to @todo_list
  end

  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'TodoList was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'TodoList was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    def todo_list_params
      params.require(:todo_list).permit(:title)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :done, 'Done' %>
    <%= f.radio_button :done, true %>
    <%= f.label :done, 'Not Done' %>
    <%= f.radio_button :done, false %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/items/edit.html.erb
edit item

<%= render 'form', item: @item %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolists</title>
    <%= csrf_meta_tags %>

      <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="page-header">
        <h1> Todo List APP </h1>
        <%= link_to 'Home', controller: 'welcome'  %>
        <%= link_to 'TodoLists', controller: 'todo_lists'  %>
      </div>
    <%= yield %>
  </body>
</html>

app/views/todo_lists/_form.html.erb
<%= form_for(todo_list) do |f| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing TodoList</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<h1>hello G</h1>

<p id="notice"><%= notice %></p>

<h1>TodoLists</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.title %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
        <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New todo_list', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<h1>New TodoList</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <strong>Todo List:</strong>
  <%= @todo_list.title %>
</h2>


<p>Items</p>
<table class="table">
  <tbody>
    <% @todo_list.items.each do |item| %>
      <tr>
        <td>
          <strong>Do:</strong>
          <%= item.title %>
        </td>
       
        <td>
          <strong>state:</strong>
          <%= item.get_state %>
        </td>
        <td>
          <%= link_to 'Edit Item', edit_todo_list_item_path(item.todo_list, item) %>
        </td>
        <td>
          <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>



<h2>Add an item:</h2>
<%= form_for([@todo_list, @todo_list.items.build]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
    <p>
    <%= f.label :done, 'Done' %>
    <%= f.radio_button :done, true %>
    <%= f.label :done, 'Not Done' %>
    <%= f.radio_button :done, false %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>



<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>A nice simple Ruby on Rails app to get accquainted :)</p>